import './css/style.css'

import { Inter } from 'next/font/google'

import AuthProvider from '@/app/(auth)/Provider'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata = {
  title: '明曦咨询',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/images/Mingxi.png' },
    ],
  },
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}